# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0  # Use the latest stable version
    hooks:
      - id: black
        name: black formatter
        files: ^population_data_analysis/
        exclude: |
          ^venv/
          ^\.venv/
          ^cdk\.out/
          ^migrations/
          ^tests/data/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort
        name: isort formatter
        files: ^population_data_analysis/
        args: ["--profile=black"]  # Match black's style
        exclude: |
          ^venv/
          ^\.venv/
          ^cdk\.out/

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1  # Use the latest stable version
    hooks:
      - id: autoflake
        name: autoflake unused imports remover
        files: ^population_data_analysis/
        args: ["--remove-all-unused-imports", "--ignore-init-module-imports"]
        exclude: |
          ^venv/
          ^\.venv/
          ^cdk\.out/

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        name: pylint linter
        files: ^population_data_analysis/
        exclude: |
          ^venv/
          ^\.venv/
          ^cdk\.out/
        args:
          - --disable=C0301,R0801,R0903,C0103,W0613,E0401,R0902,W0107,C3001,E0611,W0603,R0913,R0914,E1124,logging-fstring-interpolation

  - repo: local
    hooks:
      - id: check-clickup-ticket
        language: system
        always_run: true
        name: Ensure ClickUp ticket ID in commit message
        entry: |
          bash -c '
          grep -qE "CHIEF-[0-9]+" "$1" || (
            echo "Error: Commit message must include a ClickUp ticket ID (e.g., CHIEF-1234)" && exit 1
          )'
        stages: [commit-msg]
        args: [.git/COMMIT_EDITMSG]
